from PyQt5 import QtCore, QtGui, QtWidgets
import ida_kernwin
import idaapi


from idasync.util import pprint,update_console
from idasync.apiclient import Client
from idasync.lib import *
from PyQt5.QtCore import QTimer



class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self, manager):
        parent = idaapi.PluginForm.FormToPyQtWidget(ida_kernwin.get_current_widget())
        super().__init__(parent)
        self.manager = manager
        self.client = Client(self.manager.ip, self.manager.port)
        
        self.console_ = ["UI Inialised ✔️"]
        
        self.structs_all = {}
        self.enums_all = {}

        self.timer = QTimer(self)
        self.timer.start(self.manager.update_time)

        self.setupUi(self)
        self.setupAction()
        self.setupLabel()

        self.main_.setCurrentIndex(0) # set main first tab pannel
        self.sync_.setCurrentIndex(0) # set main::symbols tab pannel

        self.is_server_connected = False

        self.menuExit.aboutToShow.connect(self.close)

    #wrapper for gui_client
    #------------------------
    def wrapper_connectRPC(self):
        connectRPC(self)

    def wrapper_update_force_connect(self):
        update_(self, force_update=True)    

    def wrapper_update(self):
        update_(self)  

    def wrapper_structure_change(self):
        update_structure(self)

    def wrapper_enum_change(self):
        update_enum(self)

    def wrapper_instance_change(self):
        update_property(self)

    def wrapper_import_struct(self):
        import_struct(self)

    def wrapper_import_enum(self):
        import_enum(self)
        
    def wrapper_update_config(self):
        update_config(self)

    #------------------------------

    """
    Set up all actions & Buttons
    """
    def setupAction(self):
        #init button
        self.b_connect.clicked.connect(self.wrapper_connectRPC)
        self.b_update.clicked.connect(self.wrapper_update_force_connect)
        self.b_import_struct.clicked.connect(self.wrapper_import_struct)
        self.b_import_enum.clicked.connect(self.wrapper_import_enum)
        self.b_update_config.clicked.connect(self.wrapper_update_config)
        #init timer 
        self.timer.timeout.connect(self.wrapper_update)
        #init combo box
        self.structure_select.currentIndexChanged.connect(self.wrapper_structure_change)
        self.enum_select.currentIndexChanged.connect(self.wrapper_enum_change)
        self.instance_select.currentIndexChanged.connect(self.wrapper_instance_change)


    """
    Set up all labels
    """
    def setupLabel(self):
        self.l_v_ver.setText(self.manager.version)
        self.l_v_serv_status.setText("Disconnected")

        self.instance_select.addItem("No instance found")
        self.structure_select.addItem("No structure found")
        self.enum_select.addItem("No Enum found")
        self.l_v_sync_time.setText(str(self.manager.update_time))

        self.le_v_ip.setText(self.manager.ip)
        self.le_v_port.setText(str(self.manager.port))

        self.l_v_struc_size.setText("")
        self.l_p_struc_size.setText("")

        update_console(self)

    #When user close windows, must unregister the instance from idasyncserver
    def closeEvent(self, event):

        self.timer.stop()
        if self.is_server_connected:
            (ret, err) = self.client.disconnect_instance(self.manager.name_instance)
            if ret:
                pprint(f"Failed to close instance : {err}")
                
        event.accept()


    #DO NOT MODIFY/ADD/REMOVE, AUTO GENERATED WITH FORM.UI IN RESSOURCE/
    #------------------------------------------------------------------

    def setupUi(self, IDASync):
        IDASync.setObjectName("IDASync")
        IDASync.resize(1632, 837)
        IDASync.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(IDASync)
        self.centralwidget.setObjectName("centralwidget")
        self.main_ = QtWidgets.QTabWidget(self.centralwidget)
        self.main_.setEnabled(True)
        self.main_.setGeometry(QtCore.QRect(20, 20, 1571, 771))
        self.main_.setObjectName("main_")
        self.main_idasync = QtWidgets.QWidget()
        self.main_idasync.setObjectName("main_idasync")
        self.l_p_ver = QtWidgets.QLabel(self.main_idasync)
        self.l_p_ver.setGeometry(QtCore.QRect(10, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_ver.setFont(font)
        self.l_p_ver.setObjectName("l_p_ver")
        self.l_v_ver = QtWidgets.QLabel(self.main_idasync)
        self.l_v_ver.setGeometry(QtCore.QRect(180, 20, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_v_ver.setFont(font)
        self.l_v_ver.setObjectName("l_v_ver")
        self.p_console = QtWidgets.QTextEdit(self.main_idasync)
        self.p_console.setGeometry(QtCore.QRect(10, 80, 301, 621))
        self.p_console.setObjectName("p_console")
        self.b_connect = QtWidgets.QPushButton(self.main_idasync)
        self.b_connect.setGeometry(QtCore.QRect(400, 90, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.b_connect.setFont(font)
        self.b_connect.setObjectName("b_connect")
        self.l_p_serv_status = QtWidgets.QLabel(self.main_idasync)
        self.l_p_serv_status.setGeometry(QtCore.QRect(400, 210, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_serv_status.setFont(font)
        self.l_p_serv_status.setObjectName("l_p_serv_status")
        self.l_v_serv_status = QtWidgets.QLabel(self.main_idasync)
        self.l_v_serv_status.setGeometry(QtCore.QRect(480, 210, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_v_serv_status.setFont(font)
        self.l_v_serv_status.setObjectName("l_v_serv_status")
        self.sync_ = QtWidgets.QTabWidget(self.main_idasync)
        self.sync_.setGeometry(QtCore.QRect(760, 40, 781, 681))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.sync_.setPalette(palette)
        self.sync_.setAutoFillBackground(False)
        self.sync_.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.sync_.setObjectName("sync_")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.sync_.addTab(self.tab, "")
        self.sync_struct = QtWidgets.QWidget()
        self.sync_struct.setObjectName("sync_struct")
        self.structure_select = QtWidgets.QComboBox(self.sync_struct)
        self.structure_select.setGeometry(QtCore.QRect(30, 70, 391, 61))
        self.structure_select.setObjectName("structure_select")
        self.l_p_select_struct = QtWidgets.QLabel(self.sync_struct)
        self.l_p_select_struct.setGeometry(QtCore.QRect(30, 30, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_select_struct.setFont(font)
        self.l_p_select_struct.setObjectName("l_p_select_struct")
        self.p_struc_overview = QtWidgets.QTextEdit(self.sync_struct)
        self.p_struc_overview.setGeometry(QtCore.QRect(60, 190, 661, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        self.p_struc_overview.setPalette(palette)
        self.p_struc_overview.setObjectName("p_struc_overview")
        self.l_p_struc_overview = QtWidgets.QLabel(self.sync_struct)
        self.l_p_struc_overview.setGeometry(QtCore.QRect(290, 150, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_struc_overview.setFont(font)
        self.l_p_struc_overview.setObjectName("l_p_struc_overview")
        self.l_p_struc_size = QtWidgets.QLabel(self.sync_struct)
        self.l_p_struc_size.setGeometry(QtCore.QRect(470, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_struc_size.setFont(font)
        self.l_p_struc_size.setObjectName("l_p_struc_size")
        self.l_v_struc_size = QtWidgets.QLabel(self.sync_struct)
        self.l_v_struc_size.setGeometry(QtCore.QRect(560, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_v_struc_size.setFont(font)
        self.l_v_struc_size.setObjectName("l_v_struc_size")
        self.b_import_struct = QtWidgets.QPushButton(self.sync_struct)
        self.b_import_struct.setGeometry(QtCore.QRect(270, 550, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.b_import_struct.setFont(font)
        self.b_import_struct.setObjectName("b_import_struct")
        self.sync_.addTab(self.sync_struct, "")
        self.sync_enums = QtWidgets.QWidget()
        self.sync_enums.setObjectName("sync_enums")
        self.l_p_select_enum = QtWidgets.QLabel(self.sync_enums)
        self.l_p_select_enum.setGeometry(QtCore.QRect(40, 20, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_select_enum.setFont(font)
        self.l_p_select_enum.setObjectName("l_p_select_enum")
        self.enum_select = QtWidgets.QComboBox(self.sync_enums)
        self.enum_select.setGeometry(QtCore.QRect(50, 70, 391, 61))
        self.enum_select.setObjectName("enum_select")
        self.l_p_enum_size = QtWidgets.QLabel(self.sync_enums)
        self.l_p_enum_size.setGeometry(QtCore.QRect(480, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_enum_size.setFont(font)
        self.l_p_enum_size.setObjectName("l_p_enum_size")
        self.l_v_enum_size = QtWidgets.QLabel(self.sync_enums)
        self.l_v_enum_size.setGeometry(QtCore.QRect(570, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_v_enum_size.setFont(font)
        self.l_v_enum_size.setObjectName("l_v_enum_size")
        self.l_p_enum_overview = QtWidgets.QLabel(self.sync_enums)
        self.l_p_enum_overview.setGeometry(QtCore.QRect(300, 170, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_enum_overview.setFont(font)
        self.l_p_enum_overview.setObjectName("l_p_enum_overview")
        self.p_enum_overview = QtWidgets.QTextEdit(self.sync_enums)
        self.p_enum_overview.setGeometry(QtCore.QRect(60, 210, 661, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        self.p_enum_overview.setPalette(palette)
        self.p_enum_overview.setObjectName("p_enum_overview")
        self.b_import_enum = QtWidgets.QPushButton(self.sync_enums)
        self.b_import_enum.setGeometry(QtCore.QRect(270, 570, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.b_import_enum.setFont(font)
        self.b_import_enum.setObjectName("b_import_enum")
        self.sync_.addTab(self.sync_enums, "")
        self.progressBar = QtWidgets.QProgressBar(self.main_idasync)
        self.progressBar.setGeometry(QtCore.QRect(400, 240, 291, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.instance_select = QtWidgets.QComboBox(self.main_idasync)
        self.instance_select.setGeometry(QtCore.QRect(410, 370, 231, 41))
        self.instance_select.setObjectName("instance_select")
        self.l_p_instance = QtWidgets.QLabel(self.main_idasync)
        self.l_p_instance.setGeometry(QtCore.QRect(330, 300, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_instance.setFont(font)
        self.l_p_instance.setObjectName("l_p_instance")
        self.l_v_instance = QtWidgets.QLabel(self.main_idasync)
        self.l_v_instance.setGeometry(QtCore.QRect(640, 300, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_v_instance.setFont(font)
        self.l_v_instance.setObjectName("l_v_instance")
        self.l_p_select_instance = QtWidgets.QLabel(self.main_idasync)
        self.l_p_select_instance.setGeometry(QtCore.QRect(410, 340, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_select_instance.setFont(font)
        self.l_p_select_instance.setObjectName("l_p_select_instance")
        self.l_p_console = QtWidgets.QLabel(self.main_idasync)
        self.l_p_console.setGeometry(QtCore.QRect(110, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(False)
        self.l_p_console.setFont(font)
        self.l_p_console.setObjectName("l_p_console")
        self.b_update = QtWidgets.QPushButton(self.main_idasync)
        self.b_update.setGeometry(QtCore.QRect(410, 440, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.b_update.setFont(font)
        self.b_update.setObjectName("b_update")
        self.sync_.raise_()
        self.l_p_ver.raise_()
        self.l_v_ver.raise_()
        self.p_console.raise_()
        self.b_connect.raise_()
        self.l_p_serv_status.raise_()
        self.l_v_serv_status.raise_()
        self.progressBar.raise_()
        self.instance_select.raise_()
        self.l_p_instance.raise_()
        self.l_v_instance.raise_()
        self.l_p_select_instance.raise_()
        self.l_p_console.raise_()
        self.b_update.raise_()
        self.main_.addTab(self.main_idasync, "")
        self.main_opt = QtWidgets.QWidget()
        self.main_opt.setObjectName("main_opt")
        self.l_p_ip = QtWidgets.QLabel(self.main_opt)
        self.l_p_ip.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_ip.setFont(font)
        self.l_p_ip.setObjectName("l_p_ip")
        self.le_v_ip = QtWidgets.QTextEdit(self.main_opt)
        self.le_v_ip.setGeometry(QtCore.QRect(150, 20, 171, 21))
        self.le_v_ip.setObjectName("le_v_ip")
        self.l_p_port = QtWidgets.QLabel(self.main_opt)
        self.l_p_port.setGeometry(QtCore.QRect(20, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_port.setFont(font)
        self.l_p_port.setObjectName("l_p_port")
        self.le_v_port = QtWidgets.QTextEdit(self.main_opt)
        self.le_v_port.setGeometry(QtCore.QRect(150, 50, 171, 21))
        self.le_v_port.setObjectName("le_v_port")
        self.b_update_config = QtWidgets.QPushButton(self.main_opt)
        self.b_update_config.setGeometry(QtCore.QRect(550, 510, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.b_update_config.setFont(font)
        self.b_update_config.setObjectName("b_update_config")
        self.l_p_sync_time = QtWidgets.QLabel(self.main_opt)
        self.l_p_sync_time.setGeometry(QtCore.QRect(20, 80, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_sync_time.setFont(font)
        self.l_p_sync_time.setObjectName("l_p_sync_time")
        self.l_v_sync_time = QtWidgets.QTextEdit(self.main_opt)
        self.l_v_sync_time.setGeometry(QtCore.QRect(220, 80, 171, 21))
        self.l_v_sync_time.setObjectName("l_v_sync_time")
        self.main_.addTab(self.main_opt, "")
        self.main_info = QtWidgets.QWidget()
        self.main_info.setObjectName("main_info")
        self.l_p_author_2 = QtWidgets.QLabel(self.main_info)
        self.l_p_author_2.setGeometry(QtCore.QRect(570, 250, 471, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_author_2.setFont(font)
        self.l_p_author_2.setObjectName("l_p_author_2")
        self.l_p_author_3 = QtWidgets.QLabel(self.main_info)
        self.l_p_author_3.setGeometry(QtCore.QRect(520, 280, 591, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_author_3.setFont(font)
        self.l_p_author_3.setObjectName("l_p_author_3")
        self.l_p_author_4 = QtWidgets.QLabel(self.main_info)
        self.l_p_author_4.setGeometry(QtCore.QRect(630, 350, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.l_p_author_4.setFont(font)
        self.l_p_author_4.setObjectName("l_p_author_4")
        self.main_.addTab(self.main_info, "")
        IDASync.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IDASync)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1632, 22))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        IDASync.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IDASync)
        self.statusbar.setObjectName("statusbar")
        IDASync.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(IDASync)
        self.main_.setCurrentIndex(2)
        self.sync_.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(IDASync)

    def retranslateUi(self, IDASync):
        _translate = QtCore.QCoreApplication.translate
        IDASync.setWindowTitle(_translate("IDASync", "IDASync"))
        self.l_p_ver.setText(_translate("IDASync", "IDASync Version :"))
        self.l_v_ver.setText(_translate("IDASync", "version"))
        self.b_connect.setText(_translate("IDASync", "Connect to IDASync"))
        self.l_p_serv_status.setText(_translate("IDASync", "Status : "))
        self.l_v_serv_status.setText(_translate("IDASync", "serv_status"))
        self.sync_.setTabText(self.sync_.indexOf(self.tab), _translate("IDASync", "Symbol"))
        self.l_p_select_struct.setText(_translate("IDASync", "Select a Structure"))
        self.l_p_struc_overview.setText(_translate("IDASync", "Structure Overview"))
        self.l_p_struc_size.setText(_translate("IDASync", "Size : "))
        self.l_v_struc_size.setText(_translate("IDASync", "0"))
        self.b_import_struct.setText(_translate("IDASync", "Import into DB"))
        self.sync_.setTabText(self.sync_.indexOf(self.sync_struct), _translate("IDASync", "Structure"))
        self.l_p_select_enum.setText(_translate("IDASync", "Select a Enum"))
        self.l_p_enum_size.setText(_translate("IDASync", "Size : "))
        self.l_v_enum_size.setText(_translate("IDASync", "0"))
        self.l_p_enum_overview.setText(_translate("IDASync", "Enum Members"))
        self.b_import_enum.setText(_translate("IDASync", "Import into DB"))
        self.sync_.setTabText(self.sync_.indexOf(self.sync_enums), _translate("IDASync", "Enums"))
        self.l_p_instance.setText(_translate("IDASync", "Number of IDA instances connected : "))
        self.l_v_instance.setText(_translate("IDASync", "0"))
        self.l_p_select_instance.setText(_translate("IDASync", "Select Instance To Sync Data : "))
        self.l_p_console.setText(_translate("IDASync", "console"))
        self.b_update.setText(_translate("IDASync", "Force Update From Server"))
        self.main_.setTabText(self.main_.indexOf(self.main_idasync), _translate("IDASync", "IDASync"))
        self.l_p_ip.setText(_translate("IDASync", "Listening ON :"))
        self.l_p_port.setText(_translate("IDASync", "Port : "))
        self.b_update_config.setText(_translate("IDASync", "Update CONFIG"))
        self.l_p_sync_time.setText(_translate("IDASync", "Sync Server Time (ms) :"))
        self.main_.setTabText(self.main_.indexOf(self.main_opt), _translate("IDASync", "Options"))
        self.l_p_author_2.setText(_translate("IDASync", "Bug ? Report at thibault.poncetta@gmail.com"))
        self.l_p_author_3.setText(_translate("IDASync", "or create an issue at : https://github.com/0xMirasio/IDASync"))
        self.l_p_author_4.setText(_translate("IDASync", "All Pull Requests are welcomed"))
        self.main_.setTabText(self.main_.indexOf(self.main_info), _translate("IDASync", "Information"))
        self.menuExit.setTitle(_translate("IDASync", "Exit"))

